#if 0
#define _REENTRANT 1
#define SQLITE_THREADSAFE 1
#define HAVE_USLEEP 1
#define SQLITE_ENABLE_FTS3 1
#define SQLITE_ENABLE_FTS4 1
#define SQLITE_ENABLE_FTS5 1
#define SQLITE_ENABLE_JSON1 1
#define SQLITE_ENABLE_RTREE 1
#define SQLITE_ENABLE_DBSTAT_VTAB 1
#endif
